### ISSUE TITLE
Minimum width (or weight) for table columns

### ISSUE THREAD

**Issue by gergely-ujvari** [moxb/moxb#52]
Currently we have no control over how the table columns get rendered. 
But we need a feature to determine a min-width (or weigth) for some columns, not to get wrapped.

So a new column property should be introduced for , and I'm afraid that the implementation would be dependent on our ui library (semantic UI or antd).

**Comment by ck--** [comment]
Please see my suggestion in https://github.com/go-e/ves/issues/256#issuecomment-439094550

**Comment by scharf** [comment]
I think there is no need to add too many features to [`TableAnt`](https://github.com/moxb/moxb/blob/229fd27761b3bd74863925040c25d5394070fe7e/packages/antd/src/TableAnt.tsx), because it is really simple and too many features would overly complicate it.

I would directly create a new `<Table ...>...</Table>` when needed and make the standard functions (like the click handlers) part of `moxb`.

As suggested in #55, we could the use the `customData` to pass all the needed information to the UI....
